#!/bin/sh

usage="usage:
	$(basename "$0") <in> <height>

example:
	$(basename "$0") lain-ep1.mp4 128

warning:
	do not run on different files with the same name"

if [[ -z "$1" ]] || [[ -z "$2" ]]; then
	echo "$usage"
	exit 0
fi

IN="$1"
HEIGHT="$2"
PROJ="${IN%.*}"
OUT_A="${IN%.*}-outa.gif"
OUT_B="${IN%.*}-outb.gif"
OUT="${IN%.*}-out"

FRAMES="$PROJ-frames"
DITHER="$PROJ-dither"
FPSFILE="$PROJ-fps"


fps () {
	# cat it if it's saved
	cat "$FPSFILE" && exit 0

	DURATION="$(ffprobe $IN -show_entries format=duration -v quiet | grep -Po '(?<=duration=).*')"
	FRAMES="$(ffprobe -v error -select_streams v:0 -count_frames -show_entries stream=nb_read_frames $IN | grep -Po '(?<=nb_read_frames=).*')"
	FPS="$(awk "BEGIN { print "$FRAMES/$DURATION" }";)"
	echo "$FPS" > "$FPSFILE"
	cat "$FPSFILE"
}


echo "=== COUNTING FRAMES ==="
FPS=$(fps)
echo "FPS is $FPS"

mkdir -p $FRAMES
mkdir -p $DITHER

echo "=== EXTRACTING FRAMES ==="
ffmpeg -v info -i "$IN" -vf scale=-2:$HEIGHT "$FRAMES"'/%06d.png'

echo "=== DITHERING (might take a while) ==="
for f in "$FRAMES"/*; do 2ff <"$f" | jd | ff2png >"$DITHER/$(basename $f)"; done

echo "=== ENCODING ==="
ffmpeg -framerate $FPS -i $DITHER/%06d.png -lavfi palettegen=stats_mode=diff[pal],[0:v][pal]paletteuse=new=1:dither=sierra2_4a:diff_mode=rectangle -f gif $OUT_A
gifsicle -O3 -k 5 --color-method blend-diversity $OUT_A -o $OUT_B
ffmpeg -i $OUT_B -i $IN -map 0:v:0 -map 1:a:0 -c:v copy -c:a aac -b:a 512k $OUT.mov

 it seems if crf=1 then we get yuv444 and ff doesn't support that
ffmpeg -v info -r $FPS -i "$PROJ"'-dither/%06d.png' -i "$IN" -c:v libx264 -preset veryslow -crf 1 -pix_fmt yuv420p -c:a aac -b:a 256k -map 0:v:0 -map 1:a:0 $OUT.mp4
